# Generated by Django 5.1.4 on 2024-12-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0002_alter_machine_client_alter_machine_service_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BridgeB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelMashine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.bridgea'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steer_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.bridgeb'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.engine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.modelmashine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.transmission'),
        ),
    ]
